# Site settings
title: Vincent Wochnik
author: Vincent Wochnik
email: vincent@vincentwochnik.com
skype: v.wochnik
url: "http://vincentwochnik.com"
languages: ['en', 'de']

# Build settings
markdown: kramdown
encoding: utf-8
include: ['.htaccess', '_redirects']
exclude: ['Gemfile', 'Gemfile.lock']

# Plugin gems
gems:
- jekyll-compass
- jekyll-sitemap
- jekyll-language-plugin
- jekyll-email-protect

# Jekyll Language Plugin settings
language_data: data.lang.%%
language_includes_dir: _i18n

# deploy options
deploy:
- rsync -aze ssh --delete ./ vincentwochnik.com:public_html/
