# Site settings
title: Vincent Wochnik
description: Frontend Development, Software Engineering and more
author: Vincent Wochnik
keywords: >
  wochnik, vincent, vincent wochnik, software, engineer, engineering,
  development, software engineer, software development, frontend, frontend
  development, internet of things, iot
email: vincent@vincentwochnik.com
skype: v.wochnik
url: "https://vincentwochnik.com"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:slug:output_ext
encoding: utf-8
include: ['.htaccess', '_redirects']
exclude: ['Gemfile', 'Gemfile.lock', 'resources', 'README.md', 'LICENSE.md']
sass:
  style: compressed

# deploy options
deploy:
- ../.deploy-script.sh
