# Site settings
title: Vincent Wochnik
email: vincent@vincentwochnik.com
description: Web Development, Internet of Things and more
keywords: wochnik, vincent, vincent wochnik, software development, software, engineer, developer, web design, web, mobile, frontend, design, internet of things, iot
url: "http://vincentwochnik.com"

# Build settings
markdown: kramdown
gems:
- jekyll-compass
- jekyll-sitemap
- jekyll-language-plugin

# source of language data
language_data: data.lang.%%
language_includes_dir: _i18n
