source 'https://rubygems.org'
gem 'jekyll', '3.0.1'
gem 'jekyll-compass', '2.0.0', :git => 'https://github.com/chikamichi/jekyll-compass.git', :branch => 'jekyll3'
gem 'jekyll-language-plugin', '1.1.6'
gem 'jekyll-email-protect', '1.0.3'
gem 'jekyll-sitemap'
gem 'compass', '>= 1.1.0.alpha.3'
gem 'compass-normalize'
gem 'breakpoint'
gem 'susy'
