source 'https://rubygems.org'
gem 'jekyll', '>= 3.0.0'
gem 'jekyll-compass', '2.0.0', :git => 'https://github.com/chikamichi/jekyll-compass.git', :branch => 'jekyll3'
gem 'jekyll-sitemap'
gem 'compass', '>= 1.1.0.alpha.3'
gem 'compass-normalize'
gem 'breakpoint'
gem 'susy'
